In [1]:
import numpy as np

## Numpy Array

In [2]:
myList = [20, 30, 40]

In [3]:
type(myList)

list

In [4]:
np.array(myList)

array([20, 30, 40])

In [5]:
type(np.array(myList))

numpy.ndarray

In [6]:
matrixList = [[10,20,30],[20,30,40],[30,40,50]]

In [7]:
np.array(matrixList)

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

## Arange

In [8]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [9]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

## Zeros 

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

## Ones

In [14]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [15]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## Linspace

* 0'dan 20'ye kadar ardaşık sayıların farkı eşit olan 5 sayı al.

In [19]:
np.linspace(0, 20, 5)

array([ 0.,  5., 10., 15., 20.])

0'dan 15'ye kadar ardaşık sayıların farkı eşit olan 3 sayı al.

In [20]:
np.linspace(0, 15, 3)

array([ 0. ,  7.5, 15. ])

## Eye

In [21]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Random

In [26]:
np.random.randn(4,4)

array([[-0.15068745,  0.38647885,  0.1202479 , -1.12066479],
       [-0.13961336,  1.48079615,  0.01667781,  2.92241195],
       [ 0.26134686, -0.76491165,  0.0160926 ,  0.45670539],
       [-0.84095043,  1.57069506, -0.13247474,  0.94523544]])

In [27]:
np.random.randn(4)

array([ 1.22162837,  1.88536985, -1.42608857,  0.68971455])

In [28]:
np.random.randint(1,10)

9

In [29]:
np.random.randint(1, 10, 5)

array([4, 8, 5, 9, 5])

* 1'den 10'a kadar 5 tane random sayı ver.

In [30]:
myList = np.arange(20)

In [31]:
myList

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [34]:
myRandomList = np.random.randint(0, 20, 10)

In [36]:
myRandomList

array([16,  0, 10, 19, 11,  3,  2, 10,  4,  6])