## Numpy Array Methods

In [3]:
import numpy as np

In [4]:
myList = np.arange(0,30)

In [5]:
myList

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [7]:
myRandomList = np.random.randint(0,100,20)

In [8]:
myRandomList

array([ 9, 73, 11, 93, 52, 42, 41, 72,  8, 10, 19, 52, 98, 67, 25, 14, 31,
       30, 21, 99])

In [10]:
myList.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [11]:
myList.max()

29

In [12]:
myRandomList.max()

99

In [13]:
myRandomList.min()

8

In [14]:
myRandomList.argmin()

8

* argmin - argmax min veya max değerlerin hangi indexte olduğunu belirtir.

In [16]:
myList.shape

(30,)

In [17]:
reshapeList = myList.reshape(5,6)

In [18]:
reshapeList.shape

(5, 6)