In [1]:
import numpy as np

In [2]:
myArray = np.arange(0, 15)

In [3]:
myArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
myArray[5]

5

In [6]:
myArray[3:7]

array([3, 4, 5, 6])

In [7]:
myArray[3:8] = -5

In [8]:
myArray

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14])

In [9]:
otherArr = np.arange(0,25)

In [30]:
otherArr

array([ 0,  1,  2,  3, 70, 70, 70, 70, 70,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [19]:
slicingArr = otherArr[4:9]

In [20]:
slicingArr

array([4, 5, 6, 7, 8])

In [23]:
slicingArr[:] = 70

In [24]:
slicingArr

array([70, 70, 70, 70, 70])

In [25]:
exArr = np.arange(0,24)

In [26]:
exArr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [28]:
exArrCopy = exArr.copy()

In [29]:
exArrCopy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [31]:
exArrCopy[:] = 10

In [32]:
exArrCopy

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
       10, 10, 10, 10, 10, 10, 10])

In [33]:
exArr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

* Copy işlemi yaparak ana listenin verilerinin değişmesinin önüne geçtik.