## Matrix with Numpy

In [2]:
import numpy as np

In [ ]:
myList = [[10,20,30],[40,50,60],[70,80,90]]

In [ ]:
myArr = np.array(myList)

In [ ]:
myArr

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [ ]:
myArr[0]

array([10, 20, 30])

In [ ]:
myArr[0][1]

20

## Numpy Operations

In [5]:
newArr = np.random.randint(1,100,20)

In [6]:
newArr

array([ 5, 54, 22, 46, 88, 73, 29, 83, 19, 54, 32, 11,  5, 47,  5, 69, 72,
       11, 30, 28])

In [14]:
resultArr = newArr > 24

In [15]:
resultArr

array([False,  True, False,  True,  True,  True,  True,  True, False,
        True,  True, False, False,  True, False,  True,  True, False,
        True,  True])

In [16]:
newArr[resultArr]

array([54, 46, 88, 73, 29, 83, 54, 32, 47, 69, 72, 30, 28])

* 24 den büyükler geldi.

In [17]:
newArr[newArr < 24]

array([ 5, 22, 19, 11,  5,  5, 11])

In [18]:
lastArr = np.arange(0,24)

In [19]:
lastArr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [20]:
lastArr + lastArr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [21]:
lastArr * lastArr 

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [22]:
lastArr - lastArr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [23]:
np.sqrt(lastArr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [24]:
np.max(lastArr)

23

In [25]:
np.min(lastArr)

0